### ISSUE TITLE
ko-component-router seems to fail to render in IE 11

### ISSUE THREAD

**Issue by nachopants** [Profiscience/ko-component-router#118]
I'm absolutely loving ko-component-router, and it's working beautifully for our app in all browers apart from IE.

I've successfully implemented es6-promise as per the instructions, and have confirmed console>> Promise resolves in IE correctly.

However, something about the <ko-component-router> element isn't rendering (or so I suspect). No console errors, nothing, I was hoping you could provide some advice?

https://maestro-uat.heffron.com.au

**Comment by matt-hensley** [comment]
IE10 & IE11 also need Symbol and Map polyfills.

I'm using https://github.com/zloirock/core-js and importing only:
- `core-js/es6/symbol`
- `core-js/es6/map`

**Comment by caseyWebb** [comment]
@nachopants, does adding the polyfills above resolve your issue? I'm on a Mac and prefer to fire up IE as sparingly as possible, but I do know that the app that the router was created works in IE9-11. We use babel w/ the babel-polyfill. If you've still got issues, lmk.

**Comment by caseyWebb** [comment]
v4 outputs es5 code that only requires a promise lib, and appears to work ootb with IE11. Stable build is impending.

**Comment by caseyWebb** [comment]
polyfill note added to docs
