### ISSUE TITLE
pushState/replaceState usage breaks IE9, requires polyfilling

### ISSUE THREAD

**Issue by matt-hensley** [Profiscience/ko-component-router#121]
Even in hash mode, the router uses history.pushState and history.replaceState. This isn't supported in IE9.

To correct, install this HTML5 history polyfill:
`npm install --save-dev html5-history-api`

and add the following plugin configuration:
```js
    new webpack.ProvidePlugin({
        'location': 'exports?window.history.location || window.location!html5-history-api'
    })
```

**Comment by caseyWebb** [comment]
I've yet to get to playing around with the new version in IE, but whatever the process is to make it work will be documented soon. v3 should work with the above polyfill, even w/o subbing `location` iirc. It's been a while.

**Comment by caseyWebb** [comment]
I believe this is closed via https://github.com/Profiscience/ko-component-router/pull/124

thanks! 🍻
