### ISSUE TITLE
Any plans to support named states like angular-ui-router?

### ISSUE THREAD

**Issue by codymullins** [Profiscience/ko-component-router#123]
This project looks interesting, I'm currently using crossroads for routing but this looks like a decent alternative. 

I've been using angular-ui-router on another project, any thoughts on supporting named states for routes? 

i.e.

```
ko.router.state('viewUserList');
ko.router.state('viewPermissionsList');
```

or in bindings...

`data-bind="routerState: 'viewUserList'"`

These would essentially map to the routes and navigate instead of having to remember all the URLs. Could also pass in URL/query parameters as options.

**Comment by caseyWebb** [comment]
I'm not familiar with ui-router, could you elaborate a bit?

[Gitter](https://gitter.im/Profiscience/ko-component-router) may be preferable

**Comment by caseyWebb** [comment]
I don't think it's within the scope of this router. You could potentially get the state from the component name, but you don't _have_ to use the component setter. In our app, we actually use a custom middleware to set the component (it's on `ctx.router.component`).

However, with that being said, it should be trivial to implement as a small util for your app.

```javascript
import pathToRegexp from 'path-to-regexp'

const routes = {
  '/users/:id': 'users'
}

const stateMappings = Object
  .entries(routes)
  .reduce((mapping, [route, state]) => {
    mapping[state] = pathToRegexp.compile(route)
    return mapping
  }, {})

ko.router.state = function(state, params) {
  ko.router.update(stateMappings[state](params))
}

```

**Comment by caseyWebb** [comment]
This really did deserve a [wiki](https://github.com/Profiscience/ko-component-router/wiki/Named-States)

**Comment by codymullins** [comment]
thanks for following up!
