### ISSUE TITLE
Nested route requires multiple navigation in hashbang mode

### ISSUE THREAD

**Issue by matt-hensley** [Profiscience/ko-component-router#127]
Reproduced with a param http://www.webpackbin.com/4k14q8K7f
Without params, nested deeper http://www.webpackbin.com/VJeQCIt7f

Clicking the `/tasks/3` link once:
```
canonicalPath: "/tasks"
fullPath: "/#!/tasks"
path: "/tasks/3"
pathname: "/tasks"
```
Second click:
```
canonicalPath: "/tasks/3"
fullPath: "/#!/tasks/3"
path: "/3"
pathname: "/3"
```
Looks like nested routers aren't be applied immediately.

**Comment by caseyWebb** [comment]
closed via a17fbf8347e84cef774a39aa83be89f42db3b308
