### ISSUE TITLE
Error when navigating to nested route in hashbang mode

### ISSUE THREAD

**Issue by matt-hensley** [Profiscience/ko-component-router#128]
Reproduced at http://www.webpackbin.com/VJeQCIt7f

Navigating to a route with nested children routes throws 
> DOMException: Failed to execute 'dispatchEvent' on 'EventTarget': The event is already being dispatched.

Also an intermittent
> TypeError: Cannot read property 'toLowerCase' of undefined

**Comment by caseyWebb** [comment]
Happens on all unhandled routes...

...but closed in 8135bb2bff402f429f17e6024a917be61d650cbc
