### ISSUE TITLE
Nested-Routing navigation

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#14]
Hi @caseyWebb,

Is there a way to navigate programmatically from within a child-router to a route in the parent?

Considering the nested-routing sample, if I'm inside the `foo` component, how can I use the `update` function to navigate back to the base `nested-routing` page? When I try it I get a false so I assume it is not finding path in the parent router. 

Thanks in advance

**Comment by caseyWebb** [comment]
I'm working on an update which will bubble calls to `update` up through the parent routers until it finds a match; that should solve this issue.

Thanks for using the router and giving consistent input; it's super appreciated.

**Comment by caseyWebb** [comment]
The parent router should also attach itself to `ctx.$root.$router` so that app partials like navs, headers, etc. can use `ctx.update` and the `path` binding.

**Comment by caseyWebb** [comment]
As of v3.2.3 you can use `ctx.update` — and the `path` binding which calls `ctx.update` behind the scenes — bubbles it's 404s up to parent routers. When the parent router is hit if no route is matched, the page navigates away.
