### ISSUE TITLE
Assigning values invalid on ES2015 (and TypeScript) imports

### ISSUE THREAD

**Issue by Ixonal** [Profiscience/ko-component-router#143]
This came about from my using TypeScript, but also looks to be an issue for ES2015 imports (since they're intended to be the same). The bindings from an import are apparently supposed to be considered constant and unassignable. Even properties of said bindings cannot be assigned to. That being the case, assigning a value to, say, Router.config is considered an error in the new import system. Would it be possible to provide functions to assign these values instead of assigning the values directly? Say, Router.setConfig(config) and Router.setRoutes(routes).

**Comment by matt-hensley** [comment]
Check out PR #142. It has some type declarations and doesn't complain about setting the config and routes.

**Comment by Ixonal** [comment]
I did see that PR, but TypeScript doesn't like me setting Router.config still for the same reason. You're just not supposed to be able to set Router.config. From what I understand, only a module itself is supposed to be able to modify things that it exports, so it's less of an issue of TS itself, but the ES2015 import spec.

**Comment by caseyWebb** [comment]
I'll add a `setConfig` and `useRoutes` — useRoutes being composable
