### ISSUE TITLE
Error when routes bound to observable

### ISSUE THREAD

**Issue by Ixonal** [Profiscience/ko-component-router#146]
I'm having a weird issue where Knockout is turning component parameters into observables for some reason. This becomes an issue when trying to bind routes. In router.js, line 27, the Object.assign call assigns the properties of the observable instead of the properties of the value of the observable. A simple solution would be to use ko.utils.unwrapObservable to be sure that what you're assigning is a raw object.

**Comment by caseyWebb** [comment]
That would work, but honestly I'm not sure it'd be desired. Making it observable may give the impression that any changes to the routes will be picked up by the router. Can you do something similar in the client, i.e. `<ko-component-router params="routes: ko.unwrap(routes)"></ko-component-router>`?

I think you probably want to figure out why params are being turned into observables.

**Comment by Ixonal** [comment]
Well, it's not intended to be observable, it's just sort of a catch-all just in case. 

Really, it's not supposed to be an observable in my case (it's not in my view model, anyways), but Knockout converts it to one at some point before it gets passed to the routing component. Like I said, weird issue.

**Comment by caseyWebb** [comment]
That is weird. Are you using any component loaders? I can add it as a catch, I'm just curious as to why it's happening in the first place.

**Comment by Ixonal** [comment]
It probably has to do with what I'm doing with the view models. I have a function that takes an object and creates observables for all of the properties, but hides them behind getters and setters. Basically just making it so that parenthesis aren't needed all over. I guess something deep inside of the innards of knockout is detecting the read and assigning the observable, instead of the value. I'm not 100% sure though.

**Comment by caseyWebb** [comment]
@Ixonal would you mind confirming the `observable-routes` branch fixes everything for you?

**Comment by Ixonal** [comment]
@caseyWebb looks like it should. All I was doing as an interim fix that worked was putting 
```javascript
params.routes = ko.utils.unwrapObservable(params.routes);
params.base = ko.utils.unwrapObservable(params.base);
params.hashbang = ko.utils.unwrapObservable(params.hashbang);
```
as the first lines in the constructor. The toJS call should be even more reliable, and the placement looks like it'd work the same way (though, that's dependent on how the code is transpiled). Incidentally, it'd probably be a good idea to unwrap the other params in the same way for the same reason, so what about just...
```javascript
params = ko.toJS(params);
```
at the very beginning to take care of everything?

**Comment by caseyWebb** [comment]
only problem with doing that is it will wipe out any passthrough params that are supposed to be observable. for some reason, that `toJS` is breaking the tests, so I've gotta dig into that.

**Comment by Ixonal** [comment]
Good point. I guess just unwrapping routes, base, and hashbang individually would be the safest option.
