### ISSUE TITLE
Support route prefix

### ISSUE THREAD

**Issue by developermj** [Profiscience/ko-component-router#156]
Version: 4.3.1.
hashbang: true

Our site is divided into multiple different apps each with their own route prefix. I.e.:

http://somehost.com/
http://somehost.com/admin <-- site prefix

We used the "base" param on the ko-component-router element but the behavior wasn't as expected. Instead of seeing the expected route of /admin/#!/some-page we instead got the route of /#!/admin/some-page.

From reviewing the code (specifically the getter for Router.prototype.base) it seems the the latter is the expected outcome. It would seem then that the option we are looking for does not exist. Therefore, would it be possible to have a new "prefix" option added to the router to allow for what we need?

**Comment by caseyWebb** [comment]
Sounds like you want nested routing.

```javascript
ko.router.useRoutes({
  '/admin': {
    '/foo': ...,
    '/bar': ...
  }
})
```

Using CommonJS/AMD, you would break the sub-apps into separate modules.

**Comment by developermj** [comment]
Would that achieve the #! in the middle? I.e.: /admin/#!/some-page ?

We have different pages/apps with different scripts that load depending on the route that you initially hit.

**Comment by caseyWebb** [comment]
Are all of the sub-apps tied together, or are they totally independent? If each sub app defines it's own base — i.e. the admin page has a router with a base path of `/admin` — you should achieve what you're looking for.

**Comment by maxfridbe** [comment]
I'm having the same issue as this.

i **have bob.com/admin/index.html**
which can be **bob.com/admin/**
trying to route:
**bob.com/admin/#!/dashboard**

setting
`ko.router.setConfig({
    base: "",
    hashbang: true,
});`
and
`ko.components.register('app', {
    viewModel: class App {
        routes: any;
        constructor() {
            this.routes = {
                '/admin': [
                    { '/!': 'home' }
                ]...`

results in
**bob.com/#!/admin/dashboard**
if i don't do the nested routing it results in
**bob.com/#!/admin/**

**Comment by developermj** [comment]
Our apps are independent of each other. So a user going to the /admin app is in a completely different app then the user going to the / route. Setting the base doesn't achieve the expected result in the /admin page (as stated above). Is this a bug? Is it expected that the base for /admin should result in routes with /admin as the prefix?

**Comment by caseyWebb** [comment]
That would definitely be a bug; the base path should precede the `#!`. There can be some funky requirements when using the pushstate polyfill though. I'll try to get to making an example later today.

**Comment by caseyWebb** [comment]
@barake knows more about hashbang routing and IE usage than I do

**Comment by matt-hensley** [comment]
Is this happening all browsers, or just IE9 with the history polyfill?

The html5-history-api polyfill requires configuration to work with the router in general:
https://github.com/Profiscience/ko-component-router/blob/master/docs/basic.md#installation

In this case, you'd need to make your setup call look something like:
```javascript
window.history.setup('/admin', '!/', null);
```

**Comment by maxfridbe** [comment]
I am on chrome latest.
Tested it with polyfill and without, didn't try /admin in the polyfill though.

**Comment by caseyWebb** [comment]
t'was a bug, and it has been squashed. 4.4.1 should work as expected.
