### ISSUE TITLE
Hardcoded 'active-path' css class

### ISSUE THREAD

**Issue by mcgoncalves** [Profiscience/ko-component-router#165]
We're using bootstrap and when using [tabs/pills](http://getbootstrap.com/components/#nav), the selection styles are applied to the element with the class "active". 

Looking at the code trying to figure out if it could be passed as a parameter to the router, noticed that [this class is hardcoded](https://github.com/Profiscience/ko-component-router/blob/5e485970dcada56ea30dd9d3a91ef97e777d4a60/src/binding.js#L14).

Do you have any plans to make it configurable?

**Comment by caseyWebb** [comment]
I didn't, but it would be trivial

**Comment by caseyWebb** [comment]
added in dfddfc09771b62b87feb592dd5163cadee82412f

**Comment by mcgoncalves** [comment]
Thanks @caseyWebb

**Comment by cosmoKenney** [comment]
What version of this module do I need to be on in order to get this enhancement? As far a I can tell, I'm running 4.4.4. Installed via "npm install ko-component-router --save"  But I don't see any reference to activePathCSSClass in the node_modules/ko-component-router/dist/ko-component-router.js.

**Comment by caseyWebb** [comment]
@cosmoKenney try ko-component-router@next

**Comment by cosmoKenney** [comment]
@caseyWebb, I tried that, but it tried to bring in a path-to-regexp version that webpack could not load. I.e. it threw:  
_External module ''path-to-regexp'' has no default export._
So I rolled it back.

EDIT: webpack could not load the path-to-regexp brought in by ko-component-router@next

**Comment by caseyWebb** [comment]
@cosmoKenney, I'd like this working for you using `next`. For all intents and purposes, it is the stable release. I've held off on publishing to ensure the api was totally stable, and it appears to be since we've been running in production for the past several months.

Could you hop into the [gitter](https://gitter.im/Profiscience/ko-component-router) channel to figure this one out?

**Comment by cosmoKenney** [comment]
Oh shoot, I just saw this. My day is just about done. I'll hop on gitter on Monday. WebPack is giving me fits.

**Comment by caseyWebb** [comment]
pinging @cosmoKenney 😉

**Comment by cosmoKenney** [comment]
I'm over on gitter. But I'm not sure my problem is with the router or not yet.
