### ISSUE TITLE
Nested routing with a parameter in the parent

### ISSUE THREAD

**Issue by jonathaneckman** [Profiscience/ko-component-router#168]
Hi @caseyWebb 

Great work on this tool. I evaluated other routers for my project and this one is by far the best choice for a Knockout app. I am trying to follow your [example ](https://github.com/Profiscience/ko-component-router/blob/master/docs/nested.md#method-2-deep-route-object) of nested routing but could use a hand on how to navigate around the sub routes.

My config looks like this:

```
routes: any = {
        '/book/:id': ['book-workspace', {
            '/': '',
            '/page/:id': 'page-disp',
            '/page/new': 'page-new'
        }]
    };
```

When I navigate by manually changing the URL, it works fine and the child route changes as expected. However, when I try to navigate to a child route using a link, it overwrites the entire path instead of changing the child route.

For example, when I click this link from #/book/2/, I expect to be routed to #/book/2/page/new. Instead, I am routed to #/page/new.
```
<a data-bind="path: '/page/new'">New Page</a>
```

**Update**
It looks like you start with the basePath every time, so my binding should look like:

```
<a data-bind="path: 'book/' + idStoredParam() + '/page/new'">New Page</a>
```

Is that correct or is there a more elegant way?

**Comment by caseyWebb** [comment]
It depends on the location of the path binding in relation to the router you are targeting.

So, if your path binding is in the 'book-workspace', anything starting with `/` will be assumed to be at the same level as that component (adjacent to '/book/:id'). To target the child router, append `.`, i.e. `./page/new`

I just added an example that may help you:
https://github.com/Profiscience/ko-component-router/blob/master/examples/path-binding/index.js

Lastly, see: https://github.com/Profiscience/ko-component-router/blob/master/docs/path-binding.md

**Comment by jonathaneckman** [comment]
Perfect. Exactly what I needed. Thanks!
