### ISSUE TITLE
Maintain child routes

### ISSUE THREAD

**Issue by jonathaneckman** [Profiscience/ko-component-router#169]
Is it possible to navigate between nested routes like this:

Router[0]: '/book/:id', '/book/:id/edit'
Router[1]: /page/:id
Router[2]: /word/:id

I am currently at 

#!/book/2/page/3/word/6

Id like to navigate to 

#!/book/2/edit/page/3/word/6

Id expect the root router to navigate to the edit component, and all nested components to reload. I am approaching this by exploring the middleware to see if I can get the route we are leaving, get its router, and move its children to the new destination route.

**Edit**
I hacked together something that works. Ill keep digging later to see if the API can do this for me and if not, how I can run it through middleware.

```
var currentRouter = router.get(1);
var route = './';

ko.utils.arrayForEach(currentRouter.$children, (child: any) => {
   route = `${route}.${child.ctx.path}`;
});

// route = "././page/3/.word/6"

currentRouter.update(route);
```

**Comment by caseyWebb** [comment]
The child routes are unique to their parent, so `/page/:id` and `/word/:id` would also have to exist under the `/book/:id/edit` route.
