### ISSUE TITLE
How to catch non-existent routes

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#17]
Hi @caseyWebb,

I'm trying to figure out how to catch non-existent routes errors.

If the user sets an url with a route that doesn't exist, I would like to catch that error and show him a message.

Currently when the user navigates to a unknown route I get the following error:

```
Uncaught (in promise) TypeError: 
Unable to process binding "component: function () { return componentBindingValue; }"(…)
```

Thanks

**Comment by caseyWebb** [comment]
use a wildcard route, i.e. something like

``` javascript
// wherever your routes are
this.routes = {
  '/*': '404'
}

// wherever your components are
ko.components.register('404', {
  template: `
    No page found at <h3 data-bind="text: $router.pathname"></h3>
  `
})
```

**Comment by carlosagsmendes** [comment]
Thanks. Any change of capturing a not found event?

**Comment by caseyWebb** [comment]
Could you elaborate on what you mean?

**Comment by carlosagsmendes** [comment]
I was considering showing a popup message to the user if he tries to navigate to a route that is not found.  Does this make sense or is it better to always send him to the not found template?

**Comment by caseyWebb** [comment]
Oh, just add a viewmodel! The 404 component is just another route; I omitted a viewmodel for the sake of brevity.

**Comment by carlosagsmendes** [comment]
Thank you @caseyWebb. That will work fine
