### ISSUE TITLE
Single Page Application using this component

### ISSUE THREAD

**Issue by jonydev** [Profiscience/ko-component-router#171]
Hi, my project is SPG, a page contains some sections, a section contains edit mode, list view mode, and creation mode. 
I the same time, only display one mode, for example, when it's list view mode, there is a button of creating when I click create button, the container will change to creation mode, the creation button will be invisible, and the list texts can be edit. the important is, as there are some sections in one page, so the change of mode will not change the URL. 
I want to ask how could I use this ko-component-router to architecture my code.

**Comment by caseyWebb** [comment]
I'm not fully understanding you, but I'm not sure this is what you're looking for if you don't want the URL to change.

P.S. I'm available in the [gitter channel](https://gitter.im/Profiscience/ko-component-router) if you need some help setting up a project, or general q's about the router and usage.
