### ISSUE TITLE
Route parameters in ctx.params

### ISSUE THREAD

**Issue by lmaneville** [Profiscience/ko-component-router#172]
Hi, 
I am currently testing ko-component-router for our projects. It works quite good for the moment thanks.

Yet I have an issue when trying to retrieve route parameters.
As stated in ko-component-router documentation, route parameters are stored in ctx.params.
This works for params at the end of the route  but not for params in the begining.
For exemple, with the route /:language/user/:userID', ctx.params will contains 'userID' but 'language' will not be included.
Do you have the same behaviour on your side?

**Comment by caseyWebb** [comment]
to be honest, I'm not sure I've tried it :sweat_smile:

I'll take a look a bit later today.

**Comment by caseyWebb** [comment]
I wasn't able to repro in the test case above, do you think you could try to narrow down the issue?

**Comment by lmaneville** [comment]
Thank you for the test. I have the issue on a project with nested routing with Method 2 from your documentation (deep route object). So not as simple as /:language/user/:userID.
 I will try to reproduce the issue on a new project to find out what was wrong.

**Comment by caseyWebb** [comment]
ahh, you probably want to use ctx.$parent.params

**Comment by lmaneville** [comment]
Indeed.. It works better this way! 
Thank you for the help, and sorry for the time spent, I should have found it on my own
