### ISSUE TITLE
How to use this router along with RequireJs & Knockout application.

### ISSUE THREAD

**Issue by getmoble** [Profiscience/ko-component-router#173]
I dont find a single js file, which i can download and use. So I have pulled down the ko-component  using the npm command. Now in the dist folder there is a min version. Is that enough for the ko-component router to work ? 

My files looks like these 
RequireJs config
-----------------------
```
var require = {
    baseUrl: ".",
    paths: {
        "text": "scripts/text",
        "jquery": "scripts/jquery-3.1.1.min",
        "knockout": "scripts/knockout-3.4.1",
        "ko-router": "scripts/ko-router/ko-component-router.min"
    },
    shim: {
        "ko-router": {
            deps: ["knockout"]
        }
    }
};
```

Startup..
--------
```
define(["require", "exports", 'jquery', 'knockout', 'ko-router'],
function (require, exports, $, ko, router) {
    "use strict";

    ko.components.register('home',
    {
        template: '<a href="/user/1234">Show user</a>'
    });

    ko.components.register('user', {
        viewModel: (function () {
            function User(ctx) {
                console.log(ctx.params.userID);
                // 1234
            }
            return User;
        }()),
        template: '...'
    });

    router.routes = {
        '/': 'home',
        '/user/:userID': 'user'
    };

    ko.applyBindings();
});
```

And UI 
---------
```
 <div class="row">
            <ko-component-router></ko-component-router>
        </div>
```

But nothing is happening. 
Can you please guide me, what is going wrong ?

**Comment by caseyWebb** [comment]
I've got a very limited knowledge of RequireJS — but I believe it should work without shimming. The ko-component-router.js and ko-component-router.min.js are built with rollup and should be compatible with browser globals, amd, or commonjs.

**Comment by getmoble** [comment]
@caseyWebb So we can just include "ko-component-router.min.js" alone and it has everything for me to render the ko-component-router ?

**Comment by matt-hensley** [comment]
This requirejs config from one of our apps works fine:
```javascript
requirejs.config({
    paths: {
        json: '../node_modules/requirejs-plugins/src/json',
        text: '../node_modules/requirejs-plugins/lib/text',
        'knockout': '../node_modules/knockout/build/output/knockout-latest',
        'knockout-validation': '../node_modules/knockout.validation/dist/knockout.validation.min',
        'ko-component-router': '../node_modules/ko-component-router/dist/ko-component-router.min',
        'jquery': '../node_modules/jquery/dist/jquery.min',
        'underscore': '../node_modules/underscore/underscore-min'
    },
    shim: {
        'knockout-validation': ['knockout','underscore']
    }
});
```

That config will work depending on what browsers you wish to support. The router library relies on some features not present in all browsers.

[You'll need to read this page, and check the compatibility for required features.](https://github.com/Profiscience/ko-component-router/blob/master/docs/basic.md) There are some recommended polyfills (at least they're what I'm using 😄).

If you're still having problems, please create a minimal repo and one of us will take a look!

**Comment by getmoble** [comment]
Thanks, I was trying in the latest chrome, so we don't need any pollyfills right ? 
This is the minimal code, Can any one of you can help me on this ? 

https://github.com/getmoble/korouter-requirejs

**Comment by caseyWebb** [comment]
I've submitted a PR that fixes your example
