### ISSUE TITLE
Where we should call the api call for optimum experience while using ko router

### ISSUE THREAD

**Issue by getmoble** [Profiscience/ko-component-router#175]
I am using this router and it's pretty nice. But when loading the components, few components needs to load the data from the api. So what's the best way of calling them ? I write currrently in the viewmodel itself like

```
function ViewModel()
{

apiCall();

}
```

Do we have a special hook/method which router can call everytime after rendering the page. My main concern is UI is blank for sometime. Once we render the page, then calling the api will give a better experience. I can see there is a ctx.queue method. Is that something i should use, because it says resolves before page is rendered. I need something after the page is rendered, to show a busy indicator and call the api. Any examples or guidance ?

**Comment by matt-hensley** [comment]
A lazy example from one of my applications. There are other ways to achieve this but I have found structuring the routes around data loading simplifies apps. YMMV.

Use nested routing to structure the UI and do data loading, like so:
```javascript
Router.useRoutes({
    '/users': [
        ctx => api.users().then(x => ctx.users = x),
        'users'
        {
            '/:id': [
                ctx => api.user(ctx.params.id).then(x => ctx.user = x),
                'user'
            ]
        }
    ]
});
```
The `users` component will have rendered, and be waiting for the data for component `user` to load.
The router injects a `$router` variable in to the binding context that is available in the view.
Inside the `users` component use something like this to show a loading indicator:

```html
<p data-bind="async: { visible: $router.$child && $router.$child.isNavigating }">Loading...</p>
<ko-component-router data-bind="visible: !$router.isNavigating()"></ko-component-router>
```

Here is the `async` binding, from v3 of the router
```javascript
ko.bindingHandlers['async'] = {
    init(el, valueAccessor, bindings, viewModel, bindingCtx) {
        ko.tasks.schedule(() => ko.applyBindingsToNode(el, valueAccessor(), bindingCtx))
        return { controlsDescendantBindings: true }
    }
}
```

**Comment by caseyWebb** [comment]
Leave this issue open please; it's something I want to be sure to document more.

**Comment by caseyWebb** [comment]
IMO the best practice is to load data and handle loading via middleware. There is a short-coming in the current router where child routers are detached in a sense, so it is impossible to call their middleware at the same time and this can cause blank states in the UI during navigation.

This is solved in the forthcoming v5, so navigating to a deeply nested route will not transition the page until all the middleware has executed and all the data needed to render is available. This means that the current (old) page will be displayed, and then the next page rendered in one fell swoop with no blank state happening at child routers.

I've made an example that is pretty much straight out of our app [here](https://github.com/Profiscience/ko-component-router/tree/next/examples/loading-animation).

When used as intended, the UX is similar to that of GitHub. When you click a link, there is a slight delay as data is fetched, then the new page is rendered w/o any jarring or piecemeal rendering of children.

**Comment by caseyWebb** [comment]
I wrote more on the changes in middleware execution and loading UX [here](https://medium.com/@notCaseyWebb/building-a-better-router-ef42896e2e5a#.z1tsytqvb) if you're interested.
