### ISSUE TITLE
NEXT router with es5

### ISSUE THREAD

**Issue by arolonger** [Profiscience/ko-component-router#179]
Hello,

thanks for your great work. I would like to test NEXT version in my project. Do you have plans to share single file just to attach to project?

**Comment by caseyWebb** [comment]
It's not published to github, but you can install via NPM `npm install ko-component-router@next` and snag `dist/ko-component-router.min.js` (or unminified, it has sourcemaps and is huge though)

**Comment by arolonger** [comment]
Thank you 👍
