### ISSUE TITLE
Can not build project with npm install & npm start

### ISSUE THREAD

**Issue by skyline9002** [Profiscience/ko-component-router#181]
Following the readme file in the example folder, I want to build the project with npm install & npm start command. However it pop up the error message like "Can not resolve knockout "

**Comment by caseyWebb** [comment]
Whoops, `knockout` is missing from that package.json. `npm install knockout` should fix, and I'll add it to package.json.

**Comment by skyline9002** [comment]
Yes, actually I found that and fix it. :) Thank you anyway
