### ISSUE TITLE
Missing ctx.state

### ISSUE THREAD

**Issue by arolonger** [Profiscience/ko-component-router#182]
Hello once again.

I'm during tests @next router, could you share state like described below?
https://github.com/Profiscience/ko-component-router/wiki/Migrating-from-3.x-to-4.x

I used it in one place, will be easier for me to leave it and just add ctx.state support if possible.

Thanks

**Comment by caseyWebb** [comment]
`ctx.state` probably isn't coming back, at least not as a core part of the router. If all you're needing is to pass data to nested views however, you can simply attach values to `ctx` or use `with` when calling `.update()`.

**Comment by arolonger** [comment]
Ok, so thank you then. I'll try to add it into ctx.
(y)
