### ISSUE TITLE
Router isNavigating

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#20]
Hi @caseyWebb,

I need to block some UI actions while navigation is in progress. Would you consider adding a isNavigating property to the router?

I think I may be able to do it with the in and out transitions but this would be cleaner.

Thanks in advance

**Comment by caseyWebb** [comment]
Would [deferred updates](http://knockoutjs.com/documentation/deferred-updates.html) solve this? W/ `deferUpdates = true` the navigation occurs in a single batch.

I'm not opposed to adding `isNavigating`, but the above might accomplish the same with better perf

**Comment by carlosagsmendes** [comment]
Sounds good. I think there were some performance problems with deferred updates on KO 3.4 but they are about to release 3.4.1 which includes the [fix](https://github.com/knockout/knockout/commit/241c26ca82e6e4b3eaee39e3dc0a92f85bc1df0c)

Thank you
