### ISSUE TITLE
ctx.element (or ctx.router.element) missing from ctx object in middleware

### ISSUE THREAD

**Issue by sdalonzo** [Profiscience/ko-component-router#215]
Hey Casey,

We discussed this on your gitter and you asked me to make this issue. For context, I'm trying to use the example here: https://github.com/Profiscience/ko-component-router/wiki/Transition-Animations to integrate transitions, but the element property doesn't exist in the ctx. You noticed that it was removed from the source, but were not sure why.

Thanks for your help,
-steve

**Comment by cosmoKenney** [comment]
Casey, just an FYI, there are dead links in the Transition-Animations page on the Wiki, too.

**Comment by caseyWebb** [comment]
Added back in [knockout-contrib](https://github.com/Profiscience/knockout-contrib) @ 33138340ebc2b506e27abae400088ff34133ee96
