### ISSUE TITLE
How to access $router inside non-page component

### ISSUE THREAD

**Issue by kohenkatz** [Profiscience/ko-component-router#29]
I am trying to create a "Breadcrumb" component that I can use in my app to show navigation. In order to do that, I need to get the Router so I can figure out what page the user is on.

Here is a (simplified) example:

```
<app>
    <div class="header">
        <h2>Welcome to <strong>APP</strong></h2>
        <breadcrumbs params="{router: $router}"></breadcrumbs>
    </div>
    <div class="content">
        <ko-component-router params="routes: routes, base: base, hashbang: hashbang"></ko-component-router>
    </div>
</app>
```

Inside the `breadcrumbs` component, it looks up the current route and displays a list with the path to get to the current page where each part of the path is a link to go back there.

The problem is that the `$router` is added to the Knockout context when `ko-component-router` is loaded. Because the `breadcrumbs` component is added first, `$router` is not yet defined, and because `$router` is not an observable, I cannot use a `computed` to wait until it is defined.

I saw the example that uses `async: { collapsed: ko.pureComputed(function() { return $router.route().matches('/config') === null }) }`, but I am not sure how I would adapt that for my case given that the `params` attribute of the component doesn't allow other bindings inside it.

How can I get the Router here? Or is there a better way to do this?

**Comment by caseyWebb** [comment]
It's inelegant, but you could use `<div data-bind="async: { component: { name: 'breadcrumbs', params: $router } }"></div>`

Additionally, the top level router is attached to `ko.router`. From there you can traverse down via `ko.router.$child` if need be.

**Comment by caseyWebb** [comment]
Note, that async binding isn't a native ko binding. It can be found [here](https://github.com/caseyWebb/ko-component-router/blob/master/example/bindings/async.js).

Edit, I just noticed this is using `requestAnimationFrame`. You may want to change it to `ko.tasks.schedule`.

**Comment by carlosagsmendes** [comment]
@caseyWebb, using `ko.tasks.schedule` ensures that the bindings to the breadcrumbs component will only be applied after we have the router?

**Comment by kohenkatz** [comment]
Yes, it's inelegant, but it does work. Thanks!
