### ISSUE TITLE
Navigating to the same route with different route params does not update the component

### ISSUE THREAD

**Issue by Jared314** [Profiscience/ko-component-router#3]
I have a route with an `:id` parameter.

```
var routes = {
    '/a/:id': 'ComponentA'
};
```

The initial request correctly initializes `ComponentA` with the route parameters, but navigating to `/a/2` while on `/a/1` does not force the component to update.

**Comment by caseyWebb** [comment]
I've looked in to this, but I'm not sure the best way to go about it. In one case, we could reinitialize the entire component on on route change, or we could make the route params observable and react in the viewModel.

What is your use case?

**Comment by Jared314** [comment]
In this case, it's a page with a search box in the header and the page content as the search result item detail view.

The user can be on a `/a/:id` url and then navigate to another `/a/:id` url, with a different id.

I worked around the issue by reinitializing the entire component (moving [viewModel.coffee#L22](https://github.com/caseyWebb/ko-component-router/blob/master/src/lib/component/viewModel.coffee#L22) above the url check), but that does not feel like a good solution.

I would rather be passed an observable containing the parameters and react to it changing in my component's viewModel.

**Comment by caseyWebb** [comment]
It's not preferable, but for now, you can subscribe to `ko.router.current` which contains the route params. I should have some more time to work on the router shortly, but that might be able to hold you over.

**Comment by caseyWebb** [comment]
Closing as this is something that should be handled by subscribing to `ctx`

**Comment by jonathaneckman** [comment]
@caseyWebb can you give an example of your proposed workaround? I'd really like to use this router but this is my only use case.

Edit: Disregard. I just realized what you meant. Subscribe to the ctx in the child component rendered by the router and have it reload based on changes to the params.

**Comment by caseyWebb** [comment]
There is now `ctx.reloadOnParamChange`, which you can call in your viewmodel, and it will cause the component to be torn down and reloaded if any params change.

However, the recommended pattern is to merely use a computed or subscription to reload your data and run any necessary setup again.
The benefits of this approach are
  a) if there are any nested components that also fetch data (that is independent from the current dataset or parameters), these will not have to be reinitialized
  b) you have more control in your view with displaying loaders, and navigating to a new route that only has different params can draw the new page in one step, preventing a flash of white. It's kind of difficult to explain, but it just feels less  janky. I'm personally a stickler for things like this.

``` javascript
class UserViewModel {
  constructor(ctx) {
    this.ready = ko.observable(false)
    this.loading = ko.observable(false)
    this.user = ko.observable()

    // this causes a recompute whenever any observables read in it
    // changes. you could also use `.subscribe`. don't forget to dispose
    // your subscriptions!
    const subscription = ko.computed(() => {
      this.loading(true)

      UserViewModel
        .getUser(ctx.params.userId())
        .then((u) => {
          this.user(u)
          this.loading(false)
          this.ready(true)
       })
    })

    // you could also use the dispose callback, but
    // this is ran first and will prevent the changes
    // to the ctx that perform the navigation will not
    // trigger the computed to be reevaluated
    // 
    // it also prevents us from having to attach the subscription to `this`,
    // keeping it effectively private
    this.addBeforeNavigateCallback(() => subscription.dispose())
  }

  static getUser() {
    // some function that fetches the user, presumably ajax
    return Promise.resolve(/* someUserObject */)
  }
}
```

**Comment by caseyWebb** [comment]
@Slimfit, ping.

**Comment by jonathaneckman** [comment]
@caseyWebb thank you for the excellent explanation and quick reply!
