### ISSUE TITLE
subrouting example

### ISSUE THREAD

**Issue by afoninsky** [Profiscience/ko-component-router#31]
Hello.

There are two types of design: common for registered users (1), and other for registration/authorisation pages (2)

Is there way to implement subrouting? Something like:

GlobalModel:
`
this.routes = {
    '/main': 'registered-users',
    '/auth': 'registration-page',
    '/*': '404'
}
`

RegisteredUsersModel:
this.routes = {
    '/': 'main-page',
    '/user/:id': 'user-profile',
    '/*': 'internal-404'
}

where "/main" and "/main/user/123" will be with different header/footer than "/auth"?

Maybe `nested routing` will be suitable, but i comepletly dont understand it in manual :(

**Comment by caseyWebb** [comment]
You're right, nested routing is the way to go for this. You'd use something like this...

``` javascript
ko.components.register('app', {
  viewModel: class AppViemModel {
    constructor() {
      this.routes = {
        '/main/!': 'registered-users', // `!` indicates a child router is present
        '/auth': 'registration-page',
        '/*': '404'
      }
    }
  },
  template: `
    <ko-component-router params="routes: routes"></ko-component-router>
  `
})
```

``` javascript
ko.components.register('registered-users', {
  viewModel: class RegisteredUsersViewModel {
    constructor() {
      this.routes = {
        '/': 'main-page',
        '/user/:id': 'user-profile',
        '/*': '404'
      }
    }
  },
  template: `
    <main-page-header></main-page-header>
    <ko-component-router params="routes: routes"></ko-component-router>
    <main-page-footer></main-page-footer>
  `
})
```

**Comment by afoninsky** [comment]
thank you
