### ISSUE TITLE
emit a console.error when route doesn't exist 

### ISSUE THREAD

**Issue by barsh** [Profiscience/ko-component-router#33]
react-router logs an error to the console if user navigates to an invalid route.  Seems like a logical addition to ko-component-router.

When user navigates to an invalid route, an error should be logged to the console like this:

`Warning: [ko-component-router] Location "/x" did not match any routes`

For example:

```
console.error('Warning: [ko-component-router] Location "/x" did not match any routes')
```

**Comment by caseyWebb** [comment]
The router should navigate away when a route is not matched; are you not seeing this behavior?

**Comment by barsh** [comment]
It does, but explicitly informing the developer as to why that happened would help with debugging.  Here's an example:
![image](https://cloud.githubusercontent.com/assets/2644202/13995813/d63d2816-f0f8-11e5-8fb8-09dede8b17f1.png)

**Comment by caseyWebb** [comment]
Closing via e50cdc32ffe96b37e653f2413eecb440463fd89b.

Note: only throws error when path binding is used and fails, not regular anchors
