### ISSUE TITLE
.router dumb question

### ISSUE THREAD

**Issue by ghost** [Profiscience/ko-component-router#36]
Hello Casey.

I'm using your ko-component-router lib in own SPA. Didn't use KO before and it was hard to find actual routing library - yours fit perfect :)
But, i have a trouble with routing i cant fix myself.

Here is a bug:
1) Point browser to https://staging-dot-portby-web-dot-spair-api.appspot.com
2) Will redirect to https://staging-dot-portby-web-dot-spair-api.appspot.com/#!/auth

Expected behaviour: auth component should be rendered
Current behaviour: default (404) component is rendered, auth will render after page reload

Seems like .update works not like i'm expected: https://github.com/vkfont/shared-code/blob/master/src/views/default.js#L49
There are problem somewhere in my code but perhaps it's common mistake and you'll see it? At least, i think all worked as expected on amd loaders (using require.js)

Anyway, sorry for asking and thank you :)

**Comment by ghost** [comment]
Update works fine if i'll delete `synchronous: true` from component declaration

**Comment by caseyWebb** [comment]
Glad to hear it was a simple fix. If you have any more questions I opened a gitter room [here](https://gitter.im/caseyWebb/ko-component-router)
