### ISSUE TITLE
Doesn't work in Internet Explorer 11

### ISSUE THREAD

**Issue by epos** [Profiscience/ko-component-router#39]
When using Internet Explorer 11, routing crashed with the following message:

"Unable to process binding \"component: function(){return i}\"\nMessage: Unable to process binding \"component: function(){return i}\"\nMessage: 'Symbol' is undefined"

Practically, it looks like ko-component-router calls Symbol event though it set canUseSymbol=false.

The error can be seen browsing to the documentation page with IE11 or IE10: https://caseywebb.github.io/ko-component-router

**Comment by caseyWebb** [comment]
Add [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) to your project

Closing via f0206a1787f4adc6e9ecb8ffe0252a775e34c26d

**Comment by epos** [comment]
Thank you! That worked for IE10 and 11, you just made my day!
