### ISSUE TITLE
Is there a way to route the path by code?

### ISSUE THREAD

**Issue by arolonger** [Profiscience/ko-component-router#51]
Hey,
I'm wonderinf if it's possible to activate the path by JS code, not only by click.
I saw ctx.update but I'm not sure if it's the right thing I'm looking for?

**Comment by caseyWebb** [comment]
Yup, that's exactly what you're looking for. If you're outside of a routed viewmodel and don't have access to `ctx` the top level router is available at `ko.router.update`

**Comment by barsh** [comment]
@arolonger try something like this `ko.router.update('/posts/' + this.post.id + '', {}, false)`

**Comment by caseyWebb** [comment]
You could even omit those last 2 arguments. They should take those defaults.

**Comment by arolonger** [comment]
Hey,
thanks for your fast responses. ko.router.update works like I except. The problem I have is with child component. I'm guessing it's all because of my misunderstanding in some place...

My root component:

```
ko.components.register("root-container", {
            viewModel: class App {
                constructor() {
                    this.routes = {
                        '/tabs/!': 'tabs',
                        '/details/:fileId': 'details'
                    }
                }
            },
            template: 
                <ko-component-router params="
                    routes: routes,
                    base: window.location.pathname,
                    hashbang: true">
                </ko-component-router>`
        });
```

```
 ko.components.register('tabs', {
            viewModel: class App {
                constructor(ctx) {
                    this.panels = [
                        new MNTab({
                            name: "File import",
                            pathUrl: '/tabs/upload'
                        }),
                        new MNTab({
                            name: "Payment/Collection files",
                            pathUrl: '/tabs/history'
                        })
                    ];
                    this.routes = {
                        '/': 'uploadFile',
                        '/upload': 'uploadFile',
                        '/history': 'history'
                    }

                    **if (ctx.path == "/tabs/upload") {
                        ctx.query.update("/upload");
                    } else {
                        ctx.query.update("/history");
                    }**
                }
            },
            template: 
        <div class="MNTabs">
            <ul class ="MNTabs-tabs" data-bind="foreach: panels">
                <li class ="MNTabs-tab-element" data-bind="text: name, path: pathUrl></li>
            </ul>

            <ul class ="MNTabs-wrapper">
                <ko-component-router params="
                    routes: routes">
                </ko-component-router>
            </ul>
        </div>
```

Second issue is that after refresh page with nested url I have longer and longer URL per each refresh (localhost/example/////#!/tabs/history) and my both tabs have active-path class

**Comment by caseyWebb** [comment]
**`/` added on refresh**
Try changing your basepath to something like `window.location.pathname.substring(0, window.location.pathname.length - 1)` with no trailing slash

**`active-path` on both tabs**
change the path(s) from `/tabs/upload` => `/upload`. It's currently traversing up a level (since the `/tabs` part is preventing them from matching at the current level), and both routes match `/tabs/!`, marking them both active. This is something I could probably fix in the router, but I'm not terribly inclined to add anything that encourages less modularization.

If you run across any more issues don't hesitate to open them in their own bugs, that way they can serve as their own form of documentation/troubleshooting easily searchable by titles.

Cheers 🍻

**Comment by caseyWebb** [comment]
There is also a pristine [gitter](https://gitter.im/Profiscience/ko-component-router) channel just waiting for some action.
