### ISSUE TITLE
Params are not being clean when navigating between routes

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#56]
Hi @caseyWebb, when we navigate between routes, the source and destination `params` are being merged. Therefore, on as we navigate between routes we start getting params that don't belong to the route through the `ctx.params`.

As such, I think the [merge](https://github.com/Profiscience/ko-component-router/blob/master/src/utils.js#L49) should ignore the `params` property. What do you think?

**Comment by caseyWebb** [comment]
When it navigates to a new page it should clear the query object [here](https://github.com/Profiscience/ko-component-router/blob/7679c91802d7c73347e4a06e52ca2936066fdc55/src/context.js#L84). Do you have a case that they aren't being cleared?

**Comment by caseyWebb** [comment]
It seems like a shallow `extend` would suffice and solve the problem

**Comment by caseyWebb** [comment]
Fixed in 39d96df59e35ef76648fcb321d5c588552a1ce47

**Comment by carlosagsmendes** [comment]
Many thks!
