### ISSUE TITLE
Subscribing to params & path binding @ 3.8.3

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#69]
Hi @caseyWebb ,

I tested my previous issues with v3.8.3 and the limitations related to the child router - having to be sync and not using the path binding - are gone. 

Here's the [gist I'm using for testing](https://gist.github.com/carlosagsmendes/bb3c2019ed8caaed66d3e102b25b7ad4)
### 1) Issue with subscription to params

In a child router, I have a subscription to `ctx.params.id` but when navigating between tasks [the subscription is not being called](https://gist.github.com/carlosagsmendes/bb3c2019ed8caaed66d3e102b25b7ad4#file-ko-component-router-params-sample-js-L86) 

```
viewModel: class TaskDetails {
        constructor(ctx) {
            this.selectedTaskId = ko.observable(ctx.params.id());

            ctx.params.id.subscribe((newValue) => {
                alert("The new task id is " + newValue);
            });
        }
```
### 2) The issue of using the full path in the path binding in a child router persists

I [still have to use the full path](https://gist.github.com/carlosagsmendes/bb3c2019ed8caaed66d3e102b25b7ad4#file-ko-component-router-params-sample-js-L72) in the path binding.

```
 <!-- I should be able to use '/' + task.id, but it's not working. still have to use /tasks/task.id -->
<a data-bind="path: '/tasks/' + task.id(), text: task.name"></a>
```

**Comment by caseyWebb** [comment]
1) This is a side effect of https://github.com/Profiscience/ko-component-router/issues/56. Fixing in c2d7af64f2000bc8e06ac1ed1bc8af1944e50fca

**Comment by carlosagsmendes** [comment]
Thanks @caseyWebb. You closed this but the issue of using the full path in the path binding in a child router persists.

**Comment by caseyWebb** [comment]
Github caught the "fix" in the title of the commit

**Comment by caseyWebb** [comment]
@carlosagsmendes, I've been busy giving the path binding some love lately, and this should be fixed I believe. Sorry it sat so long.
