### ISSUE TITLE
Passing data between parent and child routers

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#72]
I need some help to find a way to pass data between parent and child routers.

In [my example](https://gist.github.com/carlosagsmendes/bb3c2019ed8caaed66d3e102b25b7ad4) I have a list of tasks on the parent router. When I select a task on the parent router, I want to be able to edit it on the child router.

I've passed the selected task from the parent Tasks router to the child Task Details router using the State functionality, but it doesn't work for me since I need to edit the task on the child router.

Is it ok to append the data I want to pass to the child router to its parent router context? Please take a look at the 

**On the parent router:** 

```
ko.components.register('tasks', {
    synchronous: true,
    viewModel: class Tasks {
        constructor(ctx) {
            (.....)
            //I'm attaching the data I want to pass to the child on the parent router context
            ctx.observableToBeAccessedOnTheChildRouter = this.selectedTask;

        }
```

**On the child router:**

I'm accessing the data on the child router using `ctx.$parent`:

```
    viewModel: class TaskDetails {
        constructor(ctx) {
            //Data passed from the parent router
            this.dataPassedFromParent =  ctx.$parent.observableToBeAccessedOnTheChildRouter;
```

Is this ok?

**Comment by caseyWebb** [comment]
That's a perfectly fine way to do it. Another would be to implement a model/collection layer. As your apps grow larger this becomes more and more valuable. You're able to keep your viewmodels small and concerned with UX without juggling the actual state of your data too much.

[Here's an example](https://gist.github.com/caseyWebb/27b2b0cf7948fa06983369c6376e0d37)

**Comment by carlosagsmendes** [comment]
Great to know, and thanks for the sample. Having leaner view models would be great for separation of concerns and testing.
