### ISSUE TITLE
Issue when changing paths manually

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#74]
Hi @caseyWebb,

When I change the paths on the browser there seems to be an issue with child routers. Here are my routes:

```
this.routes = {
                '/': 'overview',
                '/tasks/!': 'tasks'
```

When I try to navigate from the child router back to the overview, my path changes automatically from `http://localhost:3000/index/#!/` to `http://localhost:3000/index/#!/tasks/index/`

My base path - **index** - is being appended to the path.  

Here's a [20 sec clip](http://screencast.com/t/yAdjGMoj) showing the issue 

This may be related to the second issue reported on #69 

Here's the [code I'm using](https://gist.github.com/carlosagsmendes/aae88d365ec71dc19bbad8bbd3e77e91)

**Comment by caseyWebb** [comment]
@carlosagsmendes, I'm trying to clean up all these longstanding issues, and I think this one has been settled too. If not, could you reopen it please?

Cheers 🍻

**Comment by carlosagsmendes** [comment]
Looks good! Thanks
