### ISSUE TITLE
Nested Routing

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#8]
Hi @caseyWebb,

I was looking for a router to use with Knockout and found your project.

I need to support nested / child routing [similar to what is available in Aurelia](http://aurelia.io/get-started.html).

Are you still planning to include this feature? 

I would be only too glad to contribute with some code.

Thanks in advance.

**Comment by caseyWebb** [comment]
I absolutely want to implement nested routing, I just haven't had the opportunity to work on it yet, and I'm not sure of the best way to design the API for it. I've considered changing the api so that routes are passed into the component rather than registered globally with `ko.router.route`. This would allow a more modular approach, as components could have their own nested routers very, very easily without registering anything in the global scope.

Input?

**Comment by carlosagsmendes** [comment]
I really like Aurelia's modular approach.

Each component can implement a _configureRouter_ callback in order to have its 'own' router.

Here's an example from their getting started page:

```
export class ChildRouter{
  heading = 'Child Router';

  configureRouter(config, router){
    config.map([
      { route: ['','welcome'],  name: 'welcome',       moduleId: 'welcome',       nav: true, title:'Welcome' },
      { route: 'users',         name: 'users',         moduleId: 'users',         nav: true, title:'Github Users' },
      { route: 'child-router',  name: 'child-router',  moduleId: 'child-router',  nav: true, title:'Child Router' }
    ]);

    this.router = router;
  }
}
```

Therefore each child router can be modular keeping its own configuration. In Aurelia, they also use the callback to create a _router_ property in the viewmodel in order to make the child router available in the component.  

The trickiest part may be making all the navigation relative to the _parent_ router

**Comment by caseyWebb** [comment]
doh! apparently I typed out a response and forgot to submit it... my apologies.

I was thinking something similar to that, but a bit more explicit (I'm not a fan of lifecycle callbacks and "magic" named functions).

Here is — roughly — what I had in mind:

``` javascript
function AppRouter() {
  this.routes = {
    '/foo': 'roo',
    '/bar': 'bar',
    '/nested-router': 'child-router'
  }
}

function ChildRouter() {
  this.routes = {
    '/foo': 'foo',
    '/bar': 'bar'
  }
}

ko.components.register('app-router', { viewModel: AppRouter, template: 'AppRouter' })
ko.components.register('child-router', { viewModel: ChildRouter, template: 'ChildRouter' })
ko.components.register('foo', { viewModel: Foo, template: 'Foo' })
ko.components.register('bar', { viewModel: Bar, template: 'Bar' })
```

``` html
<app-router></app-router>

<script id="AppRouter" type="text/html">
  <a href="foo">Foo</a>
  <a href="bar">Bar</a>
  <a href="nested-router">Nested Router</a>
  <ko-component-router params="routes: routes"></ko-component-router>
</script>

<script id="ChildRouter" type="text/html">
  <a href="foo">Foo</a>
  <a href="bar">Bar</a>
  <ko-component-router params="routes: routes"></ko-component-router>
</script>
```

**Comment by caseyWebb** [comment]
Hopefully that makes sense.

**Comment by carlosagsmendes** [comment]
It looks great. 

Just to confirm, in this case we need to replicate the whole route in the child routers, i.e.: the child routes are not relative to the main router, right?

```
function AppRouter() {
  this.routes = {
    '/users/profile/:user': 'user',
    '/nested-router': 'child-router'
  }
}

function ChildRouter() {
  this.routes = {
    '/users/profile/:user/albums/sort': 'useralbums',
    '/users/profile/:user/albums/:album/details': 'useralbumdetails'
  }
}
```

**Comment by caseyWebb** [comment]
Ideally I'd like the routers to use the base path that is present in the url when they are rendered, but I feel like that could potentially cause unforeseen issues.

**Comment by caseyWebb** [comment]
I'm working on this in the little bit of spare time I have, but there is some progress coming along in the `3.0-pre` branch.

This is still under heavy development, and a lot of things are straight broken or missing.

**Comment by caseyWebb** [comment]
@carlosagsmendes, `3.0-pre` is running [here](https://caseyWebb.github.io/ko-component-router/). I haven't written tests yet, but it seems to be mostly stable as of now. I'll be working on tests this week, hopefully pushed to master by the end of the year.

**Comment by carlosagsmendes** [comment]
Thank you for the update @caseyWebb. I'll definitively save some time to test it. The documentation website looks great.

**Comment by carlosagsmendes** [comment]
Hello @caseyWebb ,

I finally got some time to test it but I can't get it to work.

Can you take a look at the following code to see if I'm missing something?

`ko-component-router` is the version from 3.0-pre 

```
import ko from 'knockout';
import './ko-component-router';

class App {
    constructor() {
        this.base = window.location.pathname.substring(0, window.location.pathname.length - 1);
        this.hashbang = false;
        this.routes = {
            '/': 'home'
        }
    }
}

ko.components.register('app', {
    viewModel: {
        createViewModel: function (params, componentInfo) {
            return new App(params);
        }
    },
    template: `
    <ko-component-router params="
      routes: routes,
      base: base,
      hashbang: hashbang">
    </ko-component-router>
  `
})

class Home {
    constructor() {
        this.title = 'Home';
    }
}

ko.components.register('home', {
    viewModel: {
        createViewModel: function (params, componentInfo) {
            return new Home(params);
        }
    },
    template: `hello from home`
})

ko.applyBindings()
```

**Comment by carlosagsmendes** [comment]
Apparently the issue is related to importing ko-component-router as a dependency with JSPM. It worked for the previous version so I will try to figure out why is not working now. Cheers

**Comment by carlosagsmendes** [comment]
Hi @caseyWebb,

v3 looks great. 

I don't know why but your sample/documentation site is not working on mobile browsers.

Also I can't get the `path` binding to work. Any suggestion?

```
<body>
    <script src="/jspm_packages/github/knockout/knockout@3.4.0/dist/knockout.js"></script>
    <script src="/jspm_packages/github/caseyWebb/ko-component-router@3.0-pre/dist/ko-component-router.js"></script>


    </script>
    <p>Router</p>
    <app></app>

    <script>
        function inTransition() {}

        function outTransition() {}

var App = function App(ctx) {

    this.base = window.location.pathname.substring(0, window.location.pathname.length - 1);
    this.hashbang = false;
    this.inTransition = inTransition;
    this.outTransition = outTransition;

    this.routes = {
        '/': 'home',
        '/user/:id': 'user'
    };
};

ko.components.register('app', {
    viewModel: {
        createViewModel: function createViewModel(params, componentInfo) {
            return new App(params);
        }
    },
    template: '\n <a data-bind="text: \'home\', path: \'/\'"></a>\n    <a data-bind="text: \'user\', path: \'/user\'"></a>\n    <ko-component-router params="\n      routes: routes,\n      base: base,\n      hashbang: hashbang">\n    </ko-component-router>\n  '
});

var Home = function Home() {

    this.title = 'Home';
};

ko.components.register('home', {
    viewModel: {
        createViewModel: function createViewModel(ctx) {
            return new Home(ctx);
        }
    },
    template: 'hello from home'
});

ko.components.register('user', {
    viewModel: function User(ctx, componentInfo) {

        ctx.state().myval = "Test";
    },
    template: 'hello from user'
});
ko.applyBindings();
    </script>

</body>

```

Thanks again

**Comment by carlosagsmendes** [comment]
I tested it with the 3 rc version and the path binding is still not working for me (it just links to #). Navigation links on the mobile site are now working on mobile devices. Thks

**Comment by caseyWebb** [comment]
@carlosagsmendes glad to hear you got it working w/ jspm & it's working on mobile again for you.

Can you try latest from `master` and let me know if the path binding still isn't working for you?

**Comment by caseyWebb** [comment]
I believe [this line](https://github.com/caseyWebb/ko-component-router/blob/master/src/binding.js#L36) should fix the issue. It allows adjacent routers to initialize before attempting to access a non-existent `$router` property

**Comment by caseyWebb** [comment]
@carlosagsmendes I'm going to close this issue, but if you're still experiencing problems w/ the latest re: the path binding, please open a new issue for it.

cheers,
casey
